version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pdu-web:latest
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
      - "5173:5173"
